@CIRRUS_VM_INSTANCE_TYPE@:
  @CIRRUS_VM_IMAGE_SELECTOR@: @CIRRUS_VM_IMAGE_NAME@

env:
  CI_REPOSITORY_URL: "@CI_REPOSITORY_URL@"
  CI_COMMIT_REF_NAME: "@CI_COMMIT_REF_NAME@"
  CI_COMMIT_SHA: "@CI_COMMIT_SHA@"
  PATH: "@PATH@"
  PKG_CONFIG_PATH: "@PKG_CONFIG_PATH@"
  PYTHON: "@PYTHON@"
  MAKE: "@MAKE@"
  VIR_TEST_VERBOSE: "1"
  VIR_TEST_DEBUG: "1"

build_task:
  install_script:
    - @UPDATE_COMMAND@
    - @UPGRADE_COMMAND@
    - @INSTALL_COMMAND@ @PKGS@
    - if test -n "@PYPI_PKGS@" ; then @PIP3@ install @PYPI_PKGS@ ; fi
  clone_script:
    - git clone --depth 100 "$CI_REPOSITORY_URL" .
    - git fetch origin "$CI_COMMIT_REF_NAME"
    - git reset --hard "$CI_COMMIT_SHA"
  build_script:
    - meson setup build
    - meson dist -C build --no-tests
    - meson compile -C build
    - meson test -C build --no-suite syntax-check
